### ISSUE TITLE
spring-cloud-config-server version issue

### ISSUE THREAD

**Issue by prateekrastogi** [livelessons-spring/building-microservices#2]
spring-cloud-config-server 1.0.1 has problems with windows while pulling the config from git repo. Please change the livelessons-parent pom file to use latest spring-cloud-starter-parent so that spring-cloud-config-server v 1.0.2 is used in dependency of configuration-cloudserver.

**Comment by Sheparzo** [comment]
Thank you @prateekrastogi for opening this GitHub issue as it lead me to success.  Once I updated the version to 1.0.2.RELEASE in the pom directly, it was able to read the config from the git repo.
